// <auto-generated />
namespace GetLabourManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gang_sheet_allocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gang_sheet_allocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201709191508512_gang_sheet_allocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
