// <auto-generated />
namespace GetLabourManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class allowance_off_onCasual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allowance_off_onCasual));
        
        string IMigrationMetadata.Id
        {
            get { return "201710111523369_allowance_off_onCasual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
