// <auto-generated />
namespace GetLabourManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GangSheetHEader_And_Items : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GangSheetHEader_And_Items));
        
        string IMigrationMetadata.Id
        {
            get { return "201708281047137_GangSheetHEader_And_Items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
